name: Image build and push action.
description: A composite action to build and push image in dockerhub.


inputs:
  dockerhub-username:
    description: "dockerhub username"
    required: true

  dockerhub-token:
    description: "dockerhub token"
    required: true

  image-name:
    description: "Image name"
    required: true

  image-tag:
    description: "Image tag"
    required: true

  dockerfile-path:
    description: "dockerfile path"
    required: true


outputs:
  result:
    description: "Result of action: success or fail"
    value: ${{ steps.final_result.ouputs.result }}


runs:
  using: composite
  steps:
  - name: Authenticate to docker hub
    shell: bash
    id: login
    run: |
      if echo ${{ inputs.dockerhub-token }} | docker login -u ${{ inputs.dockerhub-username }} --password-stdin; then
        echo "Login successful"
        echo "result=success" >> $GITHUB_OUTPUT
      else
        echo "Login failed"
        echo "result=login failed" >> $GITHUB_OUTPUT
      fi

  - name: Build docker image
    shell: bash
    id: build
    if: steps.login.outputs.result == 'success'
    run: |
      if docker build -t ${{ inputs.dockerhub-username }}/${{ inputs.image-name }}:${{ inputs.image-tag }} -f ${{ inputs.dockerfile-path }} then
        echo "Build successful"
        echo "result=success" >> $GITHUB_OUTPUT
      else
        echo "Build failed"
        echo "result=build failed" >> $GITHUB_OUTPUT
      fi

  - name: Push docker image
    shell: bash
    id: push
    if: steps.login.outputs.result=='success' and steps.build.output.result=='success'
    run: |
      if docker push ${{ inputs.dockerhub-username }}/${{ inputs.image-name }}:${{ inputs.image-tag }} then
        echo "Push successful"
        echo "result=success" >> $GITHUB_OUTPUT
      else
        echo "push failed"
        echo "result=push failed" >> $GITHUB_OUTPUT
      fi
  
  - name: Set output result
    shell: bash
    id: final_result
    run: |
      if [ "${{ steps.login.outputs.result }}" != "success" ]; then
        echo "result=failure(login failed)" >> $GITHUB_OUTPUT
      elif [ "${{ steps.build.outputs.result }}" != "success" ]; then
        echo "result=failure(build failed)" >> $GITHUB_OUTPUT
      elif [ "${{ steps.push.outputs.result }}" != "success" ]; then
        echo "result=failure(push failed)" >> $GITHUB_OUTPUT
      else
        echo "result=success" >> $GITHUB_OUTPUT
      fi


   



